# Generated by Django 6.0.7 on 2026-07-23 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("practice_areas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("attribution", models.CharField(max_length=200)),
                ("is_published", models.BooleanField(default=True)),
                ("rating", models.IntegerField(default=5)),
                (
                    "practice_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="practice_areas.practicearea",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
