# Generated by Django 6.0.7 on 2026-07-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("initials", models.CharField(max_length=5)),
                (
                    "avatar_color",
                    models.CharField(
                        choices=[("brass-light", "Brass Light"), ("moss", "Moss")],
                        default="brass-light",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
