# Generated by Django 6.0.7 on 2026-07-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PracticeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("docket_number", models.IntegerField(default=0)),
                ("headline", models.CharField(blank=True, max_length=300)),
                ("summary", models.TextField()),
                ("body", models.TextField(blank=True)),
                ("extra", models.TextField(blank=True)),
                ("services_title", models.CharField(blank=True, max_length=200)),
                ("bullet_points", models.JSONField(default=list)),
                ("stamp_label", models.CharField(blank=True, max_length=100)),
                ("stamp_body", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="practice_areas/"
                    ),
                ),
                ("meta_description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
